packages:
  - .
  - docs
catalog:
  '@vitest/coverage-v8': ^3.2.1
  vite: ^6.3.5
  vitest: ^3.2.1
  vue: ^3.5.16
overrides:
  esbuild: ^0.25.5
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
  - vue-demi
